
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AdminMenu
{

    public int AdminMenuId { get; set; }

    public string Name { get; set; }

    public int ParentId { get; set; }

    public int Order { get; set; }

}

}
