

//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPManagement.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ERPMCModelContainer : DbContext
{
    public ERPMCModelContainer()
        : base("name=ERPMCModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Customer> CustomerSet { get; set; }

    public virtual DbSet<CustomizedRDLC> CustomizedRDLCSet { get; set; }

    public virtual DbSet<FuncMenu> FuncMenuSet { get; set; }

    public virtual DbSet<AdminMenu> AdminMenuSet { get; set; }

    public virtual DbSet<ModifiedRDLC> ModifiedRDLCSet { get; set; }

    public virtual DbSet<SqlExecution> SqlExecutionSet { get; set; }

    public virtual DbSet<Log> LogSet { get; set; }

}

}

