
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FuncMenu
{

    public int FuncMenuId { get; set; }

    public string Name { get; set; }

    public string UrlSection { get; set; }

    public int ParentId { get; set; }

    public int Order { get; set; }

}

}
