
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Log
{

    public int LogId { get; set; }

    public int Type { get; set; }

    public string RelatedId { get; set; }

    public string Content { get; set; }

    public Nullable<System.DateTime> CreatedTime { get; set; }

}

}
