
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Log
{

    public int LogId { get; set; }

    public int Type { get; set; }

    public string RelatedId { get; set; }

    public string Content { get; set; }

    public Nullable<System.DateTime> CreatedTime { get; set; }

}

}
