
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ModifiedRDLC
{

    public ModifiedRDLC()
    {

        this.CustomizedRDLC = new HashSet<CustomizedRDLC>();

    }


    public int ModifiedRDLCId { get; set; }

    public string PrintId { get; set; }

    public string Version { get; set; }



    public virtual ICollection<CustomizedRDLC> CustomizedRDLC { get; set; }

}

}
