
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SqlExecution
{

    public int SqlExecutionId { get; set; }

    public int CustomerId { get; set; }

    public int DBType { get; set; }

    public System.DateTime CreatedTime { get; set; }

    public Nullable<System.DateTime> ExecutedTime { get; set; }

    public string UploadFileName { get; set; }

    public string SavedFileName { get; set; }

    public string ScriptFilePath { get; set; }

    public string BackupFileName { get; set; }

    public string BackupFilePath { get; set; }

    public string LogId { get; set; }

    public string LogFileName { get; set; }

    public string LogFilePath { get; set; }

}

}
