
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERPManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SqlExecution
{

    public int SqlExecutionId { get; set; }

    public string CustomerId { get; set; }

    public string DBType { get; set; }

    public System.DateTime CreatedTime { get; set; }

    public Nullable<System.DateTime> ExecutedTime { get; set; }

    public string ScriptFileName { get; set; }

    public string ScriptFilePath { get; set; }

    public string BackupFileName { get; set; }

    public string BackupFilePath { get; set; }

    public string LogId { get; set; }

    public string LogFileName { get; set; }

    public string LogFilePath { get; set; }

}

}
